
version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    restart: always
    environment:
      SA_PASSWORD: "MyPassword123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 20 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'MyPassword123#' -d master -i /docker-entrypoint-initdb.d/init.sql -C"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MyPassword123#", "-Q", "SELECT 1", "-C"]
      interval: 10s
      retries: 5
      start_period: 20s

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # Removed healthcheck from MongoDB to prevent dependency cycle

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: diplom-express
    restart: always
    depends_on:
      mssql:  # mssql healthcheck is still there
        condition: service_healthy
      # Removed MongoDB healthcheck dependency to avoid the cycle
    environment:
      DB_HOST_MSSQL: mssql
      DB_USER_MSSQL: sa
      DB_PASS_MSSQL: "MyPassword123#"
      DB_HOST_MONGO: mongodb
      DB_USER_MONGO: root
      DB_PASS_MONGO: toor
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["node", "app.js"]

volumes:
  mssql_data:
  mongo_data:

